services:
  backend:
    build: .
    container_name: analyzer_api
    ports:
     - "8001:10000"
    volumes:
      - .:/app  
      # - ~/.u2net:/root/.u2net 
    environment:
      - POSTGRES_SERVER=analyzer_db
      - REDIS_HOST=analyzer_redis
      - PROJECT_NAME=${PROJECT_NAME}
      - API_V1_STR=${API_V1_STR}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - STORAGE_PROVIDER=${STORAGE_PROVIDER}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_UPLOAD_PRESET=${CLOUDINARY_UPLOAD_PRESET}
    depends_on:
      - analyzer_db
      - analyzer_redis

  analyzer_db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - analyzer_data:/var/lib/postgresql/data

  analyzer_redis:
    image: redis:7-alpine
    container_name: analyzer_redis
    restart: always
    ports:
      - "6380:6379" 

volumes:
  analyzer_data: 